version: '2'

services:
    gcn-gpu:
        build:
            context: gcn-gpu
            dockerfile: Dockerfile
        image: gcr.io/gem5-test/gcn-gpu:latest
    gpu-fs:
        build:
            context: gpu-fs
            dockerfile: Dockerfile
        image: gcr.io/gem5-test/gpu-fs:latest
    sst:
        build:
            context: sst-11.1.0
            dockerfile: Dockerfile
        image: gcr.io/gem5-test/sst-env:latest
    systemc:
        build:
            context: systemc-2.3.3
            dockerfile: Dockerfile
        image: gcr.io/gem5-test/systemc-env:latest
    ubuntu-18.04_all-dependencies:
        build:
            context: ubuntu-18.04_all-dependencies
            dockerfile: Dockerfile
        image: gcr.io/gem5-test/ubuntu-18.04_all-dependencies:latest
    ubuntu-20.04_all-dependencies:
        build:
            context: ubuntu-20.04_all-dependencies
            dockerfile: Dockerfile
        image: gcr.io/gem5-test/ubuntu-20.04_all-dependencies:latest
    ubuntu-22.04_all-dependencies:
        build:
            context: ubuntu-22.04_all-dependencies
            dockerfile: Dockerfile
        image: gcr.io/gem5-test/ubuntu-22.04_all-dependencies:latest
    ubuntu-22.04_min-dependencies:
        build:
            context: ubuntu-22.04_min-dependencies
            dockerfile: Dockerfile
        image: gcr.io/gem5-test/ubuntu-22.04_min-dependencies:latest
    gcc-7:
        build:
            context: ubuntu-18.04_gcc-version
            dockerfile: Dockerfile
            args:
                - version=7
        image: gcr.io/gem5-test/gcc-version-7:latest
    gcc-8:
        build:
            context: ubuntu-18.04_gcc-version
            dockerfile: Dockerfile
            args:
                - version=8
        image: gcr.io/gem5-test/gcc-version-8:latest
    gcc-9:
        build:
            context: ubuntu-20.04_gcc-version
            dockerfile: Dockerfile
            args:
                - version=9
        image: gcr.io/gem5-test/gcc-version-9:latest
    gcc-10:
        build:
            context: ubuntu-20.04_gcc-version
            dockerfile: Dockerfile
            args:
                - version=10
        image: gcr.io/gem5-test/gcc-version-10:latest
    gcc-11:
        build:
            context: ubuntu-22.04_gcc-version
            dockerfile: Dockerfile
            args:
                - version=11
        image: gcr.io/gem5-test/gcc-version-11:latest
    gcc-12:
        build:
            context: ubuntu-22.04_gcc-version
            dockerfile: Dockerfile
            args:
                - version=12
        image: gcr.io/gem5-test/gcc-version-12:latest
    clang-6:
        build:
            context: ubuntu-18.04_clang-version
            dockerfile: Dockerfile
            args:
                - version=6.0
        image: gcr.io/gem5-test/clang-version-6.0:latest
    clang-7:
        build:
            context: ubuntu-18.04_clang-version
            dockerfile: Dockerfile
            args:
                - version=7
        image: gcr.io/gem5-test/clang-version-7:latest
    clang-8:
        build:
            context: ubuntu-18.04_clang-version
            dockerfile: Dockerfile
            args:
                - version=8
        image: gcr.io/gem5-test/clang-version-8:latest
    clang-9:
        build:
            context: ubuntu-18.04_clang-version
            dockerfile: Dockerfile
            args:
                - version=9
        image: gcr.io/gem5-test/clang-version-9:latest
    clang-10:
        build:
            context: ubuntu-20.04_clang-version
            dockerfile: Dockerfile
            args:
                - version=10
        image: gcr.io/gem5-test/clang-version-10:latest
    clang-11:
        build:
            context: ubuntu-20.04_clang-version
            dockerfile: Dockerfile
            args:
                - version=11
        image: gcr.io/gem5-test/clang-version-11:latest
    clang-12:
        build:
            context: ubuntu-20.04_clang-version
            dockerfile: Dockerfile
            args:
                - version=12
        image: gcr.io/gem5-test/clang-version-12:latest
    clang-13:
        build:
            context: ubuntu-22.04_clang-version
            dockerfile: Dockerfile
            args:
                - version=13
        image: gcr.io/gem5-test/clang-version-13:latest
    clang-14:
        build:
            context: ubuntu-22.04_clang-version
            dockerfile: Dockerfile
            args:
                - version=14
        image: gcr.io/gem5-test/clang-version-14:latest
    llvm-gnu-cross-compiler-riscv64:
        build:
            context: llvm-gnu-cross-compiler-riscv64
            dockerfile: Dockerfile
        image: gcr.io/gem5-test/llvm-gnu-cross-compiler-riscv64:latest
    gem5-all-min-dependencies:
        build:
            context: gem5-all-min-dependencies
            dockerfile: Dockerfile
        image: gcr.io/gem5-test/gem5-all-min-dependencies:latest
